name: tab_container
description: Animated and customisable tab view widget.
  It's self-contained, so you can just pass in children and tabs, or
  also use a controller, change the tab side, add color(s), and more.
version: 2.0.0
homepage: https://github.com/sourcemain/tab_container
repository: https://github.com/sourcemain/tab_container

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
